describe('template spec', () => {
  it('login successfully', () => {
    cy.visit('http://localhost:3000/')
    cy.url().should('include', 'localhost:3000')
    cy.get('span[name="log"]')
      .click()
    cy.get('input[name="email"]')
      .focus()
      .type('1')
    cy.get('input[name="pwd"]')
      .focus()
      .type('1')
    cy.get('button[name="log-btn"]')
      .click()
  })

  it('create new listings successfully', () => {
    cy.visit('http://localhost:3000/Welcome')
    cy.url().should('include', 'localhost:3000/Welcome')
    cy.get('button[name="host"]')
      .click()
    cy.get('button[name="create-new"]')
      .click()
    cy.get('input[name="title"]')
      .focus()
      .type('Terraces')
    cy.get('input[name="address"]')
      .focus()
      .type('Syd')
    cy.get('button[name="create-it"]')
      .click()
  })

  it('see all other listings successfully', () => {
    cy.visit('http://localhost:3000/Welcome')
    cy.url().should('include', 'localhost:3000/Welcome')
    cy.get('button[name="all"]')
      .click()
  })

  it('sign up successfully', () => {
    cy.visit('http://localhost:3000/')
    cy.url().should('include', 'localhost:3000')
    cy.get('span[name="sign"]')
      .click()
    cy.get('input[name="email1"]')
      .focus()
      .type('6')
    cy.get('input[name="name1"]')
      .focus()
      .type('6')
    cy.get('input[name="pwd1"]')
      .focus()
      .type('6')
    cy.get('input[name="pwd2"]')
      .focus()
      .type('6')
    cy.get('button[name="sign-btn"]')
      .click()
  })

  it('log out successfully', () => {
    cy.visit('http://localhost:3000/Welcome')
    cy.url().should('include', 'localhost:3000/Welcome')
    cy.get('button[name="out"]')
      .click()
  })
})